from enum import Enum


class MeasurementQualityIssueCode(Enum):
    """Codes stables des faits de qualité de mesure."""

    CLIPPING_DETECTED = "CLIPPING_DETECTED"
    LOW_SIGNAL_LEVEL = "LOW_SIGNAL_LEVEL"
    HIGH_NOISE_FLOOR = "HIGH_NOISE_FLOOR"
    INSUFFICIENT_DYNAMIC_RANGE = "INSUFFICIENT_DYNAMIC_RANGE"
    INVALID_DIRECT_PEAK = "INVALID_DIRECT_PEAK"
    INSUFFICIENT_IR_DURATION = "INSUFFICIENT_IR_DURATION"
    CHANNEL_SAMPLE_RATE_MISMATCH = "CHANNEL_SAMPLE_RATE_MISMATCH"
    CHANNEL_LENGTH_MISMATCH = "CHANNEL_LENGTH_MISMATCH"
    CHANNEL_TIMING_MISMATCH = "CHANNEL_TIMING_MISMATCH"
    MISSING_REQUIRED_CHANNEL = "MISSING_REQUIRED_CHANNEL"
    INCONSISTENT_MEASUREMENT_METADATA = (
        "INCONSISTENT_MEASUREMENT_METADATA"
    )
