from enum import Enum


class HypothesisCode(Enum):
    ASYMMETRIC_SPEAKER_ROOM_INTERACTION = (
        "ASYMMETRIC_SPEAKER_ROOM_INTERACTION"
    )
    MODAL_BASS_PERSISTENCE = "MODAL_BASS_PERSISTENCE"
    DOMINANT_EARLY_REFLECTION_INTERACTION = (
        "DOMINANT_EARLY_REFLECTION_INTERACTION"
    )
    SBIR_PLACEMENT_INTERACTION = "SBIR_PLACEMENT_INTERACTION"


class HypothesisStatus(Enum):
    SUPPORTED = "SUPPORTED"
    PLAUSIBLE = "PLAUSIBLE"
    INCONCLUSIVE = "INCONCLUSIVE"
    CONTRADICTED = "CONTRADICTED"


class EvidenceRole(Enum):
    SUPPORTING = "SUPPORTING"
    COUNTER_EVIDENCE = "COUNTER_EVIDENCE"
    CONTEXT = "CONTEXT"


class VerificationActionType(Enum):
    COMPARE = "COMPARE"
    MEASURE = "MEASURE"
    TEMPORARY_MOVE = "TEMPORARY_MOVE"
    TEMPORARY_MASK = "TEMPORARY_MASK"
