class GlobalDomainCode:
    MEASUREMENT_QUALITY = "MEASUREMENT_QUALITY"
    BASS_DECAY = "BASS_DECAY"
    RT60 = "RT60"
    ETC = "ETC"
    CLARITY = "CLARITY"
    SPATIAL = "SPATIAL"
    DIRECT_REVERBERANT = "DIRECT_REVERBERANT"


class SourceAnalysisCode:
    ROOM_GEOMETRY = "RoomGeometry"
    MEASUREMENT_QUALITY = "MeasurementQualityAnalysis"
    MEASUREMENT_READINESS = "MeasurementReadinessAnalysis"
    GLOBAL = "GlobalAnalysis"
    BASS_DECAY = "BassDecayAnalysis"
    BASS_DECAY_CORRELATION = "BassDecayCorrelationAnalysis"
    RT60 = "RT60Analysis"
    ETC = "ETCAnalysis"
    CLARITY = "ClarityAnalysis"
    SPATIAL = "SpatialAnalysis"
    CLARITY_CORRELATION = "ClarityCorrelationAnalysis"
    SPATIAL_CORRELATION = "SpatialCorrelationAnalysis"
    ETC_REFLECTION_CORRELATION = "ETCReflectionCorrelationAnalysis"
    DIRECT_REVERBERANT = "DirectReverberantAnalysis"
    DIRECT_REVERBERANT_CORRELATION = (
        "DirectReverberantCorrelationAnalysis"
    )


class GlobalCorrelationCode:
    BASS_DECAY_MODAL_INTERACTION = "BASS_DECAY_MODAL_INTERACTION"
    BASS_DECAY_RT60_INTERACTION = "BASS_DECAY_RT60_INTERACTION"
    BASS_DECAY_DRR_INTERACTION = "BASS_DECAY_DRR_INTERACTION"
    ETC_SPATIAL_ASYMMETRY = "ETC_SPATIAL_ASYMMETRY"
    RT60_CLARITY_DECAY_INTERACTION = "RT60_CLARITY_DECAY_INTERACTION"
    ETC_CLARITY_EARLY_ENERGY_INTERACTION = (
        "ETC_CLARITY_EARLY_ENERGY_INTERACTION"
    )
    SPATIAL_STEREO_ALIGNMENT = "SPATIAL_STEREO_ALIGNMENT"
    LOW_DRR_DECAY_INTERACTION = "LOW_DRR_DECAY_INTERACTION"
    DRR_EARLY_REFLECTION_INTERACTION = "DRR_EARLY_REFLECTION_INTERACTION"
    DRR_SPATIAL_ASYMMETRY = "DRR_SPATIAL_ASYMMETRY"


class RecommendationCode:
    RETAKE_CLIPPED_MEASUREMENT = "RETAKE_CLIPPED_MEASUREMENT"
    IMPROVE_SIGNAL_TO_NOISE = "IMPROVE_SIGNAL_TO_NOISE"
    FIX_CHANNEL_TIMING = "FIX_CHANNEL_TIMING"
    COMPLETE_REQUIRED_CHANNELS = "COMPLETE_REQUIRED_CHANNELS"
    CHECK_MEASUREMENT_METADATA = "CHECK_MEASUREMENT_METADATA"
    INVESTIGATE_LONG_BASS_DECAY = "INVESTIGATE_LONG_BASS_DECAY"
    CHECK_MODAL_EXCITATION = "CHECK_MODAL_EXCITATION"
    COMPARE_BASS_DECAY_CHANNELS = "COMPARE_BASS_DECAY_CHANNELS"
    CHECK_EARLY_REFLECTION_SYMMETRY = "CHECK_EARLY_REFLECTION_SYMMETRY"
    INVESTIGATE_RT60_CHANNEL_DIFFERENCES = (
        "INVESTIGATE_RT60_CHANNEL_DIFFERENCES"
    )
    INVESTIGATE_DOMINANT_EARLY_REFLECTIONS = (
        "INVESTIGATE_DOMINANT_EARLY_REFLECTIONS"
    )
    VERIFY_TIME_ALIGNMENT = "VERIFY_TIME_ALIGNMENT"
    IMPROVE_DIRECT_SOUND_DOMINANCE = "IMPROVE_DIRECT_SOUND_DOMINANCE"
    INVESTIGATE_DRR_CHANNEL_DIFFERENCES = (
        "INVESTIGATE_DRR_CHANNEL_DIFFERENCES"
    )
    APPLY_EARLY_REFLECTION_TREATMENT = (
        "APPLY_EARLY_REFLECTION_TREATMENT"
    )


class FactCode:
    BASS_DECAY_USABLE_BAND_COUNT = "bass_decay.usable_band_count"
    BASS_DECAY_MAXIMUM_DECAY_TIME = "bass_decay.maximum_decay_time"
    BASS_DECAY_SIGNIFICANT_DIFFERENCE_COUNT = (
        "bass_decay.significant_difference_count"
    )
    BASS_DECAY_CORRELATION_COUNT = "bass_decay.correlation_count"
    BASS_DECAY_MODAL_MATCH_COUNT = "bass_decay.modal_match.count"
    RT60_BROADBAND_MEAN = "rt60.broadband_mean"
    RT60_INTERCHANNEL_HOMOGENEITY = "rt60.interchannel_homogeneity"
    RT60_RELIABLE_DIFFERENCE_COUNT = "rt60.reliable_difference_count"
    ETC_COMMON_EVENT_COUNT = "etc.common_event_count"
    ETC_CHANNEL_SPECIFIC_EVENT_COUNT = "etc.channel_specific_event_count"
    ETC_REFLECTION_DOMINANT_UNMATCHED_EVENT_COUNT = (
        "etc_reflection.dominant_unmatched_event_count"
    )
    CLARITY_CHANNEL_ASYMMETRY_COUNT = "clarity.channel_asymmetry_count"
    CLARITY_CORRELATION_COUNT = "clarity.correlation_count"
    SPATIAL_TECHNICAL_CENTER_STABILITY = (
        "spatial.technical_center_stability"
    )
    SPATIAL_CORRELATION_COUNT = "spatial.correlation_count"
    DRR_BROADBAND_DB = "direct_reverberant.broadband_drr_db"
    DRR_ASYMMETRIC_BAND_COUNT = (
        "direct_reverberant.asymmetric_band_count"
    )
    DRR_CORRELATION_COUNT = "direct_reverberant.correlation_count"
